<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_TestPopup" Id="{d9b4814f-f421-40ad-a7c7-c4267f370936}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestPopup
VAR_INPUT
	i_PopupReq : BOOL;// 1=Popup, 0=No popup
END_VAR
VAR_OUTPUT
	o_PopupResult : BOOL;
END_VAR
VAR
	bPopupResult : BOOL;
	iPopupN : INT;
	bButtonPressed : BOOL;
	bPopupOK : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[o_PopupResult := bPopupResult;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>